In [4]:
import pandas as pd
import numpy as np
import os

cp2_path = "/home/qcx679/hantang/UAAG2/data/2018_PNAS_DeltaG/210526_CP2_average_lin_fit_Delta_G.csv"
puma_path = "/home/qcx679/hantang/UAAG2/data/2018_PNAS_DeltaG/210526_PUMA_exp_fit_Delta_G.csv"

cp2_df = pd.read_csv(cp2_path)
puma_df = pd.read_csv(puma_path)

# aa_result = "/home/qcx679/hantang/UAAG2/ProteinGymSampling/runCP2_NAA_half_mask_scaled/DN7A_SACS2/aa_distribution.csv"
aa_result = "/home/qcx679/hantang/UAAG2/ProteinGymSampling/runPUMA_NAA_half_mask_scaled/DN7A_SACS2/aa_distribution.csv"
result_exp = pd.read_csv(aa_result)

In [5]:
result_exp.sort_values(by=["pos"], inplace=True)

In [6]:
result_exp

,aa,pos,ALA,CYS,ASP,GLU,PHE,GLY,HIS,ILE,...,MeA,MeB,MeF,2th,3th,YMe,2Np,Bzt,UNK,INV
0,GLU,130,100.0,2.0,36.0,48.0,15.0,NaN,19.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359,98
22,GLU,131,100.0,3.0,80.0,87.0,41.0,NaN,72.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,292,11
3,GLU,132,100.0,2.0,65.0,68.0,8.0,NaN,29.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,352,51
17,TRP,133,100.0,10.0,21.0,29.0,32.0,NaN,68.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,286,13
7,ALA,134,100.0,25.0,NaN,17.0,87.0,NaN,70.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,314,6
13,ARG,135,100.0,9.0,16.0,19.0,3.0,NaN,17.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,378,43
16,GLU,136,100.0,3.0,83.0,98.0,72.0,NaN,49.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,322,12
24,ILE,137,100.0,56.0,2.0,56.0,85.0,NaN,82.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,313,6
25,ALA,139,100.0,NaN,48.0,56.0,30.0,NaN,29.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347,11
14,GLN,140,100.0,66.0,2.0,24.0,28.0,NaN,47.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325,6
12,LEU,141,100.0,91.0,NaN,2.0,98.0,NaN,83.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,340,10
5,ARG,142,100.0,17.0,8.0,4.0,11.0,NaN,38.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341,28
1,ARG,143,100.0,2.0,29.0,34.0,NaN,NaN,12.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,363,49
2,ILE,144,100.0,56.0,NaN,20.0,70.0,NaN,78.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,289,6
6,ALA,145,100.0,2.0,45.0,48.0,50.0,NaN,49.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370,15
18,ASP,146,100.0,15.0,96.0,97.0,67.0,NaN,20.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380,6
15,ASP,147,100.0,3.0,32.0,56.0,38.0,NaN,37.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,344,19
10,LEU,148,100.0,65.0,NaN,19.0,87.0,NaN,74.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,279,11
11,ASN,149,100.0,3.0,49.0,66.0,41.0,NaN,91.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,265,7
23,ALA,150,100.0,2.0,42.0,47.0,32.0,NaN,47.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359,16
20,GLN,151,100.0,2.0,11.0,21.0,9.0,NaN,27.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350,26
4,TYR,152,100.0,30.0,3.0,3.0,56.0,NaN,69.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,272,18
21,GLU,153,100.0,4.0,30.0,38.0,7.0,NaN,25.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,355,15
19,ARG,154,100.0,10.0,24.0,24.0,3.0,NaN,16.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,372,59
8,ARG,155,100.0,4.0,29.0,30.0,9.0,NaN,35.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,337,43
9,MET,156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1069,29

In [ ]:
aa_map = {
        'ALA': 'A',
        'CYS': 'C',
        'ASP': 'D',
        'GLU': 'E',
        'PHE': 'F',
        'GLY': 'G',
        'HIS': 'H',
        'ILE': 'I',
        'LYS': 'K',
        'LEU': 'L',
        'MET': 'M',
        'ASN': 'N',
        'PRO': 'P',
        'GLN': 'Q',
        'ARG': 'R',
        'SER': 'S',
        'THR': 'T',
        'VAL': 'V',
        'TRP': 'W',
        'TYR': 'Y',
        'UNK': 'X',
        'INV': 'Z'
    } 
# reverse the mapping
aa_map = {v: k for k, v in aa_map.items()}

In [3]:
puma_df

,aa,Gly,Ala,Ser,Thr,Val,Leu,Ile,Asp,Glu,...,MeG,MeA,MeB,MeF,2Th,3Th,YMe,2Np,Bzt,DAl
0,0R,0.10,0.25,0.09,0.16,0.16,0.06,0.13,0.24,0.24,...,0.24,0.15,0.24,-0.46,-0.60,-0.35,-0.26,-1.71,-0.95,0.58
1,1V,0.05,-0.05,0.11,0.16,NaN,-0.16,-0.10,0.19,0.14,...,0.03,-0.03,0.10,-0.40,-0.73,-0.61,-0.08,-1.07,-1.05,0.55
2,2E,-0.07,-0.14,-0.08,-0.07,-0.40,-0.52,-0.56,-0.08,NaN,...,0.02,-0.04,-0.12,-0.77,-0.73,-0.75,-0.24,-1.35,-1.20,0.48
3,3E,-0.15,-0.42,-0.11,-0.30,-0.66,-0.76,-0.70,-0.21,NaN,...,0.15,0.17,0.14,0.02,-1.12,-0.96,-1.00,-1.05,-1.11,0.41
4,4E,0.83,0.81,0.55,0.49,0.53,0.30,0.06,-0.19,NaN,...,0.53,0.40,0.33,-0.57,-0.50,-0.03,0.48,-0.48,-0.33,1.38
5,5E,0.19,-0.14,-0.13,0.06,0.21,0.03,0.08,-0.41,NaN,...,0.32,0.47,0.78,1.31,-0.17,-0.07,0.07,-0.68,-0.32,0.97
6,6W,1.29,0.94,1.13,0.58,0.56,0.69,0.12,1.77,1.87,...,1.61,1.79,1.69,1.11,0.51,0.88,0.83,-0.04,0.16,1.58
7,7A,1.67,NaN,0.90,0.81,-0.64,-0.66,-0.69,1.88,0.63,...,2.12,1.35,0.62,0.72,-0.92,-0.38,-0.15,-0.97,-0.64,0.80
8,8R,1.34,-0.30,0.13,1.09,0.16,0.56,0.13,0.40,-0.10,...,2.68,4.28,2.18,2.15,0.28,0.40,1.30,0.12,0.54,2.53
9,9E,1.17,0.48,0.38,0.57,0.23,0.15,-0.06,0.32,NaN,...,2.66,2.38,1.78,1.83,-0.53,-0.12,0.51,-0.52,-0.43,1.82
10,10I,2.97,1.53,2.90,2.06,0.78,0.68,NaN,2.39,2.14,...,2.61,4.05,2.36,2.82,0.60,0.93,1.79,0.18,-0.01,3.88
11,11G,NaN,-0.62,0.58,0.79,-0.32,0.46,-0.68,1.83,1.77,...,3.56,3.11,2.16,2.25,0.00,0.36,0.22,-0.70,-0.40,1.36
12,12A,0.81,NaN,0.39,0.33,0.17,-0.80,-0.41,-0.36,-0.53,...,3.02,2.81,1.51,3.00,-0.48,-0.05,0.58,-0.22,-0.32,0.93
13,13Q,0.68,-0.25,0.46,0.38,-0.04,-0.49,-0.49,1.05,0.28,...,4.13,4.13,2.10,2.59,-1.28,-0.89,-0.04,-0.04,-0.53,2.66
14,14L,2.56,2.33,2.67,2.42,2.57,NaN,1.05,2.46,2.37,...,3.23,3.04,3.17,3.44,1.66,2.71,2.81,1.59,0.89,3.28
15,15R,1.99,0.83,1.39,1.25,0.79,1.01,0.94,2.45,2.23,...,3.59,2.92,2.26,2.77,1.52,1.99,2.47,1.34,1.12,2.83
16,16R,1.29,0.09,0.70,0.68,0.32,0.22,0.13,0.89,0.37,...,3.38,3.22,2.11,2.91,0.51,0.60,1.06,0.31,0.12,1.88
17,17A,1.48,NaN,0.84,0.59,-1.26,-1.64,-1.87,1.52,1.53,...,3.42,3.91,1.67,3.52,-1.68,-1.51,-1.04,-0.99,-1.12,2.75
18,18A,-1.71,NaN,1.13,1.57,1.81,1.80,1.93,1.23,1.72,...,2.81,3.71,3.35,1.87,0.78,2.34,1.70,0.64,1.26,2.45
19,19D,2.18,1.99,2.17,2.34,2.09,2.15,1.76,NaN,1.67,...,2.68,2.66,2.51,2.57,1.92,1.83,2.16,1.60,1.45,3.34
20,20D,0.82,-0.32,0.16,0.31,-0.08,-0.24,-0.33,NaN,-0.36,...,2.51,2.74,1.45,2.71,-0.24,-0.04,0.21,0.11,-0.09,1.95
21,21L,1.19,2.51,2.52,1.76,1.72,NaN,2.40,1.43,2.46,...,4.39,1.81,1.95,1.62,0.89,1.16,1.36,2.75,1.89,2.40
22,22N,2.51,1.55,1.65,1.30,1.52,1.57,1.58,0.85,1.43,...,2.77,2.82,1.69,2.44,0.44,0.84,1.40,0.66,0.44,2.77
23,23A,0.78,NaN,0.28,0.57,0.76,0.39,0.78,0.38,0.11,...,2.43,2.24,2.34,2.16,0.55,0.46,0.56,-0.23,0.17,2.29
24,24Q,0.95,0.38,0.42,0.42,0.24,-0.18,-0.01,0.76,-0.12,...,3.88,2.52,2.89,2.23,-0.41,-0.20,-0.48,-1.17,-0.43,1.82
25,25Y,4.00,1.88,2.27,1.42,1.25,1.59,1.06,2.84,3.04,...,5.75,5.53,1.63,4.55,0.18,0.15,0.18,0.30,0.09,9.92
26,26E,1.14,0.52,0.47,0.43,0.41,0.01,0.58,0.65,NaN,...,2.88,2.17,1.72,1.71,0.60,0.60,1.55,2.11,1.99,2.69
27,27R,0.78,0.27,0.56,0.67,0.93,0.51,0.44,1.19,0.91,...,0.86,0.91,1.35,1.29,0.26,0.36,0.91,0.34,0.78,1.63
28,28R,0.13,0.12,0.44,0.45,0.28,-0.26,-0.22,0.97,0.84,...,0.35,0.70,0.82,0.87,-0.14,-0.14,0.03,-0.41,-0.16,0.51
29,29R,0.43,0.95,0.67,0.51,0.69,0.65,0.60,0.64,1.44,...,1.01,0.80,0.99,0.63,-0.30,0.06,1.03,0.74,0.50,1.56
30,30Q,0.26,-0.16,0.06,0.22,0.10,0.11,-0.12,0.19,0.23,...,0.47,1.14,1.09,0.43,-0.69,-0.14,-0.06,0.55,0.27,1.34
31,31E,-0.03,-0.13,-0.20,0.02,-0.13,-0.18,-0.18,0.16,NaN,...,-0.01,0.01,0.14,0.26,-0.21,0.16,0.16,-0.21,-0.18,0.33
32,32E,-0.01,-0.23,-0.11,-0.05,-0.06,-0.16,-0.11,0.10,NaN,...,-0.23,-0.06,0.05,0.19,-0.37,-0.04,0.29,-0.08,-0.14,0.27
33,33Q,0.05,0.06,0.19,0.04,0.09,0.07,0.10,-0.05,0.23,...,-0.16,-0.06,0.38,0.46,-0.12,-0.20,0.57,-0.31,0.08,1.29

In [9]:
puma_df['pos'] = cp2_df['aa'].str.extract(r'(\d+)').astype(int)

In [9]:
cp2_df['pos'] += 2

In [11]:
#  set the value of pos to the corresponding value of index
for i in range(len(puma_df)):
    puma_df.loc[i, 'pos'] = i

In [13]:
puma_df['pos'] += 127

In [14]:
puma_df

,aa,Gly,Ala,Ser,Thr,Val,Leu,Ile,Asp,Glu,...,MeA,MeB,MeF,2Th,3Th,YMe,2Np,Bzt,DAl,pos
0,0R,0.10,0.25,0.09,0.16,0.16,0.06,0.13,0.24,0.24,...,0.15,0.24,-0.46,-0.60,-0.35,-0.26,-1.71,-0.95,0.58,127.0
1,1V,0.05,-0.05,0.11,0.16,NaN,-0.16,-0.10,0.19,0.14,...,-0.03,0.10,-0.40,-0.73,-0.61,-0.08,-1.07,-1.05,0.55,128.0
2,2E,-0.07,-0.14,-0.08,-0.07,-0.40,-0.52,-0.56,-0.08,NaN,...,-0.04,-0.12,-0.77,-0.73,-0.75,-0.24,-1.35,-1.20,0.48,129.0
3,3E,-0.15,-0.42,-0.11,-0.30,-0.66,-0.76,-0.70,-0.21,NaN,...,0.17,0.14,0.02,-1.12,-0.96,-1.00,-1.05,-1.11,0.41,130.0
4,4E,0.83,0.81,0.55,0.49,0.53,0.30,0.06,-0.19,NaN,...,0.40,0.33,-0.57,-0.50,-0.03,0.48,-0.48,-0.33,1.38,131.0
5,5E,0.19,-0.14,-0.13,0.06,0.21,0.03,0.08,-0.41,NaN,...,0.47,0.78,1.31,-0.17,-0.07,0.07,-0.68,-0.32,0.97,132.0
6,6W,1.29,0.94,1.13,0.58,0.56,0.69,0.12,1.77,1.87,...,1.79,1.69,1.11,0.51,0.88,0.83,-0.04,0.16,1.58,133.0
7,7A,1.67,NaN,0.90,0.81,-0.64,-0.66,-0.69,1.88,0.63,...,1.35,0.62,0.72,-0.92,-0.38,-0.15,-0.97,-0.64,0.80,134.0
8,8R,1.34,-0.30,0.13,1.09,0.16,0.56,0.13,0.40,-0.10,...,4.28,2.18,2.15,0.28,0.40,1.30,0.12,0.54,2.53,135.0
9,9E,1.17,0.48,0.38,0.57,0.23,0.15,-0.06,0.32,NaN,...,2.38,1.78,1.83,-0.53,-0.12,0.51,-0.52,-0.43,1.82,136.0
10,10I,2.97,1.53,2.90,2.06,0.78,0.68,NaN,2.39,2.14,...,4.05,2.36,2.82,0.60,0.93,1.79,0.18,-0.01,3.88,137.0
11,11G,NaN,-0.62,0.58,0.79,-0.32,0.46,-0.68,1.83,1.77,...,3.11,2.16,2.25,0.00,0.36,0.22,-0.70,-0.40,1.36,138.0
12,12A,0.81,NaN,0.39,0.33,0.17,-0.80,-0.41,-0.36,-0.53,...,2.81,1.51,3.00,-0.48,-0.05,0.58,-0.22,-0.32,0.93,139.0
13,13Q,0.68,-0.25,0.46,0.38,-0.04,-0.49,-0.49,1.05,0.28,...,4.13,2.10,2.59,-1.28,-0.89,-0.04,-0.04,-0.53,2.66,140.0
14,14L,2.56,2.33,2.67,2.42,2.57,NaN,1.05,2.46,2.37,...,3.04,3.17,3.44,1.66,2.71,2.81,1.59,0.89,3.28,141.0
15,15R,1.99,0.83,1.39,1.25,0.79,1.01,0.94,2.45,2.23,...,2.92,2.26,2.77,1.52,1.99,2.47,1.34,1.12,2.83,142.0
16,16R,1.29,0.09,0.70,0.68,0.32,0.22,0.13,0.89,0.37,...,3.22,2.11,2.91,0.51,0.60,1.06,0.31,0.12,1.88,143.0
17,17A,1.48,NaN,0.84,0.59,-1.26,-1.64,-1.87,1.52,1.53,...,3.91,1.67,3.52,-1.68,-1.51,-1.04,-0.99,-1.12,2.75,144.0
18,18A,-1.71,NaN,1.13,1.57,1.81,1.80,1.93,1.23,1.72,...,3.71,3.35,1.87,0.78,2.34,1.70,0.64,1.26,2.45,145.0
19,19D,2.18,1.99,2.17,2.34,2.09,2.15,1.76,NaN,1.67,...,2.66,2.51,2.57,1.92,1.83,2.16,1.60,1.45,3.34,146.0
20,20D,0.82,-0.32,0.16,0.31,-0.08,-0.24,-0.33,NaN,-0.36,...,2.74,1.45,2.71,-0.24,-0.04,0.21,0.11,-0.09,1.95,147.0
21,21L,1.19,2.51,2.52,1.76,1.72,NaN,2.40,1.43,2.46,...,1.81,1.95,1.62,0.89,1.16,1.36,2.75,1.89,2.40,148.0
22,22N,2.51,1.55,1.65,1.30,1.52,1.57,1.58,0.85,1.43,...,2.82,1.69,2.44,0.44,0.84,1.40,0.66,0.44,2.77,149.0
23,23A,0.78,NaN,0.28,0.57,0.76,0.39,0.78,0.38,0.11,...,2.24,2.34,2.16,0.55,0.46,0.56,-0.23,0.17,2.29,150.0
24,24Q,0.95,0.38,0.42,0.42,0.24,-0.18,-0.01,0.76,-0.12,...,2.52,2.89,2.23,-0.41,-0.20,-0.48,-1.17,-0.43,1.82,151.0
25,25Y,4.00,1.88,2.27,1.42,1.25,1.59,1.06,2.84,3.04,...,5.53,1.63,4.55,0.18,0.15,0.18,0.30,0.09,9.92,152.0
26,26E,1.14,0.52,0.47,0.43,0.41,0.01,0.58,0.65,NaN,...,2.17,1.72,1.71,0.60,0.60,1.55,2.11,1.99,2.69,153.0
27,27R,0.78,0.27,0.56,0.67,0.93,0.51,0.44,1.19,0.91,...,0.91,1.35,1.29,0.26,0.36,0.91,0.34,0.78,1.63,154.0
28,28R,0.13,0.12,0.44,0.45,0.28,-0.26,-0.22,0.97,0.84,...,0.70,0.82,0.87,-0.14,-0.14,0.03,-0.41,-0.16,0.51,155.0
29,29R,0.43,0.95,0.67,0.51,0.69,0.65,0.60,0.64,1.44,...,0.80,0.99,0.63,-0.30,0.06,1.03,0.74,0.50,1.56,156.0
30,30Q,0.26,-0.16,0.06,0.22,0.10,0.11,-0.12,0.19,0.23,...,1.14,1.09,0.43,-0.69,-0.14,-0.06,0.55,0.27,1.34,157.0
31,31E,-0.03,-0.13,-0.20,0.02,-0.13,-0.18,-0.18,0.16,NaN,...,0.01,0.14,0.26,-0.21,0.16,0.16,-0.21,-0.18,0.33,158.0
32,32E,-0.01,-0.23,-0.11,-0.05,-0.06,-0.16,-0.11,0.10,NaN,...,-0.06,0.05,0.19,-0.37,-0.04,0.29,-0.08,-0.14,0.27,159.0
33,33Q,0.05,0.06,0.19,0.04,0.09,0.07,0.10,-0.05,0.23,...,-0.06,0.38,0.46,-0.12,-0.20,0.57,-0.31,0.08,1.29,160.0

In [15]:
puma_df['aa'] = puma_df['aa'].str.extract(r'([A-Z])')

In [18]:
aa_map = {
        'ALA': 'A',
        'CYS': 'C',
        'ASP': 'D',
        'GLU': 'E',
        'PHE': 'F',
        'GLY': 'G',
        'HIS': 'H',
        'ILE': 'I',
        'LYS': 'K',
        'LEU': 'L',
        'MET': 'M',
        'ASN': 'N',
        'PRO': 'P',
        'GLN': 'Q',
        'ARG': 'R',
        'SER': 'S',
        'THR': 'T',
        'VAL': 'V',
        'TRP': 'W',
        'TYR': 'Y',
        'UNK': 'X',
        'INV': 'Z'
    } 
# reverse the mapping
aa_map = {v: k for k, v in aa_map.items()}

In [19]:
# replace the values in the 'aa' column using the mapping
puma_df['aa'] = puma_df['aa'].replace(aa_map)

In [20]:
puma_df

,aa,Gly,Ala,Ser,Thr,Val,Leu,Ile,Asp,Glu,...,MeA,MeB,MeF,2Th,3Th,YMe,2Np,Bzt,DAl,pos
0,ARG,0.10,0.25,0.09,0.16,0.16,0.06,0.13,0.24,0.24,...,0.15,0.24,-0.46,-0.60,-0.35,-0.26,-1.71,-0.95,0.58,127.0
1,VAL,0.05,-0.05,0.11,0.16,NaN,-0.16,-0.10,0.19,0.14,...,-0.03,0.10,-0.40,-0.73,-0.61,-0.08,-1.07,-1.05,0.55,128.0
2,GLU,-0.07,-0.14,-0.08,-0.07,-0.40,-0.52,-0.56,-0.08,NaN,...,-0.04,-0.12,-0.77,-0.73,-0.75,-0.24,-1.35,-1.20,0.48,129.0
3,GLU,-0.15,-0.42,-0.11,-0.30,-0.66,-0.76,-0.70,-0.21,NaN,...,0.17,0.14,0.02,-1.12,-0.96,-1.00,-1.05,-1.11,0.41,130.0
4,GLU,0.83,0.81,0.55,0.49,0.53,0.30,0.06,-0.19,NaN,...,0.40,0.33,-0.57,-0.50,-0.03,0.48,-0.48,-0.33,1.38,131.0
5,GLU,0.19,-0.14,-0.13,0.06,0.21,0.03,0.08,-0.41,NaN,...,0.47,0.78,1.31,-0.17,-0.07,0.07,-0.68,-0.32,0.97,132.0
6,TRP,1.29,0.94,1.13,0.58,0.56,0.69,0.12,1.77,1.87,...,1.79,1.69,1.11,0.51,0.88,0.83,-0.04,0.16,1.58,133.0
7,ALA,1.67,NaN,0.90,0.81,-0.64,-0.66,-0.69,1.88,0.63,...,1.35,0.62,0.72,-0.92,-0.38,-0.15,-0.97,-0.64,0.80,134.0
8,ARG,1.34,-0.30,0.13,1.09,0.16,0.56,0.13,0.40,-0.10,...,4.28,2.18,2.15,0.28,0.40,1.30,0.12,0.54,2.53,135.0
9,GLU,1.17,0.48,0.38,0.57,0.23,0.15,-0.06,0.32,NaN,...,2.38,1.78,1.83,-0.53,-0.12,0.51,-0.52,-0.43,1.82,136.0
10,ILE,2.97,1.53,2.90,2.06,0.78,0.68,NaN,2.39,2.14,...,4.05,2.36,2.82,0.60,0.93,1.79,0.18,-0.01,3.88,137.0
11,GLY,NaN,-0.62,0.58,0.79,-0.32,0.46,-0.68,1.83,1.77,...,3.11,2.16,2.25,0.00,0.36,0.22,-0.70,-0.40,1.36,138.0
12,ALA,0.81,NaN,0.39,0.33,0.17,-0.80,-0.41,-0.36,-0.53,...,2.81,1.51,3.00,-0.48,-0.05,0.58,-0.22,-0.32,0.93,139.0
13,GLN,0.68,-0.25,0.46,0.38,-0.04,-0.49,-0.49,1.05,0.28,...,4.13,2.10,2.59,-1.28,-0.89,-0.04,-0.04,-0.53,2.66,140.0
14,LEU,2.56,2.33,2.67,2.42,2.57,NaN,1.05,2.46,2.37,...,3.04,3.17,3.44,1.66,2.71,2.81,1.59,0.89,3.28,141.0
15,ARG,1.99,0.83,1.39,1.25,0.79,1.01,0.94,2.45,2.23,...,2.92,2.26,2.77,1.52,1.99,2.47,1.34,1.12,2.83,142.0
16,ARG,1.29,0.09,0.70,0.68,0.32,0.22,0.13,0.89,0.37,...,3.22,2.11,2.91,0.51,0.60,1.06,0.31,0.12,1.88,143.0
17,ALA,1.48,NaN,0.84,0.59,-1.26,-1.64,-1.87,1.52,1.53,...,3.91,1.67,3.52,-1.68,-1.51,-1.04,-0.99,-1.12,2.75,144.0
18,ALA,-1.71,NaN,1.13,1.57,1.81,1.80,1.93,1.23,1.72,...,3.71,3.35,1.87,0.78,2.34,1.70,0.64,1.26,2.45,145.0
19,ASP,2.18,1.99,2.17,2.34,2.09,2.15,1.76,NaN,1.67,...,2.66,2.51,2.57,1.92,1.83,2.16,1.60,1.45,3.34,146.0
20,ASP,0.82,-0.32,0.16,0.31,-0.08,-0.24,-0.33,NaN,-0.36,...,2.74,1.45,2.71,-0.24,-0.04,0.21,0.11,-0.09,1.95,147.0
21,LEU,1.19,2.51,2.52,1.76,1.72,NaN,2.40,1.43,2.46,...,1.81,1.95,1.62,0.89,1.16,1.36,2.75,1.89,2.40,148.0
22,ASN,2.51,1.55,1.65,1.30,1.52,1.57,1.58,0.85,1.43,...,2.82,1.69,2.44,0.44,0.84,1.40,0.66,0.44,2.77,149.0
23,ALA,0.78,NaN,0.28,0.57,0.76,0.39,0.78,0.38,0.11,...,2.24,2.34,2.16,0.55,0.46,0.56,-0.23,0.17,2.29,150.0
24,GLN,0.95,0.38,0.42,0.42,0.24,-0.18,-0.01,0.76,-0.12,...,2.52,2.89,2.23,-0.41,-0.20,-0.48,-1.17,-0.43,1.82,151.0
25,TYR,4.00,1.88,2.27,1.42,1.25,1.59,1.06,2.84,3.04,...,5.53,1.63,4.55,0.18,0.15,0.18,0.30,0.09,9.92,152.0
26,GLU,1.14,0.52,0.47,0.43,0.41,0.01,0.58,0.65,NaN,...,2.17,1.72,1.71,0.60,0.60,1.55,2.11,1.99,2.69,153.0
27,ARG,0.78,0.27,0.56,0.67,0.93,0.51,0.44,1.19,0.91,...,0.91,1.35,1.29,0.26,0.36,0.91,0.34,0.78,1.63,154.0
28,ARG,0.13,0.12,0.44,0.45,0.28,-0.26,-0.22,0.97,0.84,...,0.70,0.82,0.87,-0.14,-0.14,0.03,-0.41,-0.16,0.51,155.0
29,ARG,0.43,0.95,0.67,0.51,0.69,0.65,0.60,0.64,1.44,...,0.80,0.99,0.63,-0.30,0.06,1.03,0.74,0.50,1.56,156.0
30,GLN,0.26,-0.16,0.06,0.22,0.10,0.11,-0.12,0.19,0.23,...,1.14,1.09,0.43,-0.69,-0.14,-0.06,0.55,0.27,1.34,157.0
31,GLU,-0.03,-0.13,-0.20,0.02,-0.13,-0.18,-0.18,0.16,NaN,...,0.01,0.14,0.26,-0.21,0.16,0.16,-0.21,-0.18,0.33,158.0
32,GLU,-0.01,-0.23,-0.11,-0.05,-0.06,-0.16,-0.11,0.10,NaN,...,-0.06,0.05,0.19,-0.37,-0.04,0.29,-0.08,-0.14,0.27,159.0
33,GLN,0.05,0.06,0.19,0.04,0.09,0.07,0.10,-0.05,0.23,...,-0.06,0.38,0.46,-0.12,-0.20,0.57,-0.31,0.08,1.29,160.0

In [20]:
result_exp

,aa,pos,ALA,CYS,ASP,GLU,PHE,GLY,HIS,ILE,...,MeA,MeB,MeF,2th,3th,YMe,2Np,Bzt,UNK,INV
10,VAL,2,100,61,1.0,6,93,NaN,81,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341,12
7,TYR,3,100,19,14.0,39,43,NaN,68,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,283,22
9,ASN,4,100,22,12.0,36,60,NaN,87,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,252,13
2,THR,5,100,12,23.0,47,55,NaN,63,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311,11
0,ARG,6,100,36,3.0,4,23,NaN,42,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,320,11
4,SER,7,100,13,6.0,37,95,NaN,84,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,295,7
6,TRP,9,100,77,NaN,37,58,NaN,83,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242,17
8,ARG,10,100,59,NaN,3,8,NaN,31,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,331,21
3,TRP,11,100,71,NaN,4,91,NaN,96,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,234,12
1,TYR,12,100,2,15.0,30,23,NaN,50,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,332,31
5,THR,13,100,18,25.0,54,60,NaN,72,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,302,17

In [24]:
cp2_df.columns

Index(['aa', 'Gly', 'Ala', 'Ser', 'Thr', 'Val', 'Leu', 'Ile', 'Asp', 'Glu',
       'Asn', 'Gln', 'Arg', 'Lys', 'His', 'Trp', 'Tyr', 'Phe', 'Cys', 'Pro',
       'Abu', 'Nva', 'Nle', 'Ahp', 'Aoc', 'TMe', 'hSM', 'tBu', 'Cpa', 'Cha',
       'Aib', 'MeG', 'MeA', 'MeB', 'MeF', '2Th', '3Th', 'YMe', '2Np', 'Bzt',
       'DAl', 'pos'],
      dtype='object')

In [26]:
cp2_df

,aa,Gly,Ala,Ser,Thr,Val,Leu,Ile,Asp,Glu,...,MeA,MeB,MeF,2Th,3Th,YMe,2Np,Bzt,DAl,pos
0,VAL,2.05,0.78,0.49,0.73,NaN,0.81,0.37,2.50,2.11,...,1.44,0.19,2.01,0.31,0.99,0.83,1.33,1.84,2.39,2
1,TYR,0.74,0.10,0.11,-0.19,-0.16,-0.02,-0.15,0.54,0.27,...,1.21,-0.10,2.25,-0.09,0.17,0.07,0.71,0.85,0.86,3
2,ASN,0.77,0.43,0.46,0.18,-0.24,1.32,0.29,1.47,1.67,...,0.09,0.39,1.53,0.85,1.34,1.18,1.86,1.96,2.35,4
3,THR,-0.01,-0.47,-0.43,NaN,0.14,0.92,1.42,0.77,0.79,...,1.18,1.21,2.00,0.03,0.54,0.36,1.18,0.69,1.73,5
4,ARG,2.92,2.59,2.68,2.96,2.55,2.45,2.52,2.94,3.18,...,2.19,2.94,3.17,1.70,2.51,1.60,1.83,2.59,3.49,6
5,SER,1.27,1.42,NaN,1.64,1.87,2.45,1.89,2.81,2.99,...,2.68,2.95,3.09,1.39,1.88,2.27,2.61,2.62,2.91,7
6,GLY,NaN,2.21,2.32,2.80,2.83,2.72,2.68,3.03,3.00,...,2.54,3.14,3.11,1.97,2.57,2.34,2.55,2.46,0.11,8
7,TRP,3.02,2.93,2.58,2.52,2.42,1.16,2.05,2.53,2.85,...,2.43,2.97,1.70,0.74,1.19,1.52,0.93,-0.39,3.55,9
8,ARG,2.13,0.76,1.26,0.10,-0.69,0.39,-0.27,2.99,2.67,...,2.70,1.62,2.99,0.94,1.47,1.79,2.21,1.23,3.05,10
9,TRP,2.22,2.16,2.31,2.34,1.72,1.22,1.12,2.93,2.54,...,2.73,3.07,3.22,-0.08,0.31,-0.32,-0.41,-0.04,3.22,11
10,TYR,1.39,0.68,0.81,0.61,0.00,0.43,0.21,1.20,1.32,...,1.88,1.82,2.00,-0.28,0.08,-0.34,0.07,0.22,1.99,12
11,THR,0.32,0.13,-0.04,NaN,0.20,-0.09,0.11,0.24,0.19,...,-0.18,0.29,0.35,-0.89,-0.80,-0.88,-0.98,-1.02,1.39,13

In [22]:
aa_list = ['Gly', 'Ala', 'Ser', 'Thr', 'Val', 'Leu', 'Ile', 'Asp', 'Glu',
       'Asn', 'Gln', 'Arg', 'Lys', 'His', 'Trp', 'Tyr', 'Phe', 'Cys', 'Pro',
       'Abu', 'Nva', 'Nle', 'Ahp', 'Aoc', 'TMe', 'hSM', 'tBu', 'Cpa', 'Cha',
       'Aib', 'MeG', 'MeA', 'MeB', 'MeF', '2Th', '3Th', 'YMe', '2Np', 'Bzt',
       'DAl']

In [21]:
# convert cp2_df to another DataFrame, as the format of column 1: aa, column 2: pos, column 3: target, column 4: value
puma_reframe = pd.DataFrame(columns=['aa', 'pos', 'target', 'value'])

In [23]:
for index, row in puma_df.iterrows():
    aa = row['aa']
    pos = row['pos']
    for target in aa_list:
        value = row[target]
        
        # check if the value is not NaN
        
    # convert target to all capital
    
    # create a new DataFrame with the same structure as cp2_reframe
        new_row = pd.DataFrame({'aa': [aa], 'pos': [pos], 'target': [target.upper()], 'value': [value]})
    
    # append the new DataFrame to cp2_reframe
        puma_reframe = pd.concat([puma_reframe, new_row], ignore_index=True)

In [24]:
puma_reframe

       aa    pos target  value
0     ARG  127.0    GLY   0.10
1     ARG  127.0    ALA   0.25
2     ARG  127.0    SER   0.09
3     ARG  127.0    THR   0.16
4     ARG  127.0    VAL   0.16
...   ...    ...    ...    ...
1355  GLN  160.0    3TH  -0.20
1356  GLN  160.0    YME   0.57
1357  GLN  160.0    2NP  -0.31
1358  GLN  160.0    BZT   0.08
1359  GLN  160.0    DAL   1.29

[1360 rows x 4 columns]

In [26]:
puma_reframe.to_csv('/home/qcx679/hantang/UAAG2/data/uaa_benchmark_csv/PUMA_reframe.csv', index=False)